### ISSUE TITLE
Link to Petition in ShareModal does not work

### ISSUE THREAD

**Issue by sigmarstern** [iris-dni/iris-frontend#126]
When clicking the clicking the link on ShareModal, i.e. after supporting a petition, nothing happens. Console says `Warning: A path must be pathname + search + hash only, not a fully qualified URL like "http://localhost:8000/petitions/1TJdm"`.

I guess we have to split up the link's url (petition path only) and its label (full petition label).

Maybe like [this](https://github.com/iris-dni/iris-frontend/blob/33b9ba7f50315bf9d35704c270303932b29bf375/src/components/RespondedToPetition/index.js#L27-L30)?

**Comment by Tom-Bonnike** [comment]
#138
