### ISSUE TITLE
Add proper copywriting

### ISSUE THREAD

**Issue by BennoDev** [iris-dni/iris-frontend#264]
This issue serves as a reminder, there will be a PR for this shortly.

- [x] Homepage: answered petitions widget text (EN/DE)
- [x] Petitions browse page: Successful but not answered petitions filter term (EN/DE)

The translations have been marked in iris by 
```javascript
//TODO: Add proper copywriting
```

**Comment by artibella** [comment]
No references in code found. Closing this
