### ISSUE TITLE
Default theme styling changes

### ISSUE THREAD

**Issue by Tom-Bonnike** [iris-dni/iris-frontend#71]
## Menu
- [ ] Add transition on active to the border

Mobile:
- [x] Set active border at the left of items instead of at the bottom (see https://cloud.githubusercontent.com/assets/9154236/18470289/2a0ca228-79ac-11e6-9a07-a82c37accea7.png)
- [ ] Full-width create-petition button, anchored at the bottom of the screen
- [ ] Staggering burger-icon animation (either the use of `top` or some logic problem in the animation)
## Petition browsing
- [ ] New filters
- [ ] New teaser on mobile

**Comment by eschaefer** [comment]
Double scrollbar can be killed with `html, body { min-height: 100%; }` on base styles
