### ISSUE TITLE
Petitions city-filtering & pagination

### ISSUE THREAD

**Issue by Tom-Bonnike** [iris-dni/iris-frontend#78]
- [x] Double loading of petitions
- [x] Going from city-filtered /petitions to /petitions doesn‘t reset the dynamic headline and title  #87 
- [x] Fix search input position on mobile #87
- [x] Move `fetchCity` to server to stop FOUC - http://g.recordit.co/s6pk2kAym1.gif
- [ ] Improve 'Loading' states and add spinner
  - Underway in https://github.com/iris-dni/iris-frontend/pull/86

**Comment by mattberridge** [comment]
@sigmarstern "Handle params mis-spelling" an you take a look if @artibella says this is still a must-have?

see:
https://edenspiekermann.slack.com/archives/az-iris/p1473863665000180
